### ISSUE TITLE
Error Extracting vendor

### ISSUE THREAD

**Issue by Hadenix** [ShivamKumarJha/android_tools#14]
```
Extracting vendor
Traceback (most recent call last):
  File "/home/hadenix/Загрузки/android_tools/tools/Firmware_extractor/tools/sdat2img.py", line 142, in <module>
    main(sys.argv)
  File "/home/hadenix/Загрузки/android_tools/tools/Firmware_extractor/tools/sdat2img.py", line 87, in main
    version, new_blocks, commands = parse_transfer_list_file(TRANSFER_LIST_FILE)
  File "/home/hadenix/Загрузки/android_tools/tools/Firmware_extractor/tools/sdat2img.py", line 55, in parse_transfer_list_file
    trans_list = open(TRANSFER_LIST_FILE, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'vendor.transfer.list'

```

**Comment by Hadenix** [comment]
on the pc such an error. on the laptop I checked everything is fine
